[technote]
id = "SITCOMTN-143"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-143.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-143"
github_default_branch = "main"
date_created = 2024-10-10T19:38:41Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name = {given = "Paulina", family = "Venegas"}
internal_id = "venegasp"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "Avenida Juan Cisternas #1500, La Serena, Chile"


[[technote.authors]]
name = {given = "Yijung", family = "Kang"}
internal_id = "kangy"
orcid = "https://orcid.org/0000-0002-5261-5803"
[[technote.authors.affiliations]]
name = "Kavli Institute for Particle Astrophysics and Cosmology"
internal_id = "SLAC-Kavli"
address = "SLAC National Accelerator Laboratory, Stanford University, Stanford, CA 94025, USA"

[[technote.authors]]
internal_id = "quintb"
orcid = "https://orcid.org/0000-0002-1557-3560"
name = {given = "Bruno C.", family = "Quint"}
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"

[[technote.authors]]
internal_id = "kakoon"
orcid = "https://orcid.org/0000-0002-7295-2743"
name = {given = "HyeYun", family = "Park"}
[[technote.authors.affiliations]]
name = "Duke University"
